### ISSUE TITLE
Deprecate this repo

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-head-only#186]
Head-only formulae are a bad experience for our users: we can’t bottle them; they frequently break due to upstream changes; and we don’t have any automatic update mechanism so they quickly become outdated.

Let’s try to get stable releases for as many formulae as possible.

## Imported in core
- [x] agedu.rb imported in core (https://github.com/Homebrew/homebrew/pull/47967)
- [x] choose.rb: imported in core (https://github.com/Homebrew/homebrew/pull/46137)
- [x] codemod.rb: imported in core (https://github.com/Homebrew/homebrew/pull/46099)
- [x] dromeaudio.rb: imported in core (https://github.com/Homebrew/homebrew/pull/46163)
- [x] git-svn-abandon.rb: migrated to core (https://github.com/Homebrew/homebrew/pull/49083)
- [x] git-utils.rb: migrated to core (https://github.com/Homebrew/homebrew-core/pull/584)
- [x] gerrit-tools.rb: migrated to core (https://github.com/Homebrew/homebrew/pull/49068)
- [x] hg-fast-export.rb: importing into core (https://github.com/Homebrew/homebrew-core/pull/4112)
- [x] httpdiff.rb (https://github.com/jgrahamc/httpdiff/issues/19, https://github.com/Homebrew/homebrew-core/pull/4514)
- [x] jxrlib.rb: migrated to core (https://github.com/Homebrew/homebrew-core/pull/3914)
- [x] kerl.rb: migrated to core (https://github.com/Homebrew/homebrew-core/pull/296)
- [x] moz-git-tools.rb: imported into core (https://github.com/Homebrew/homebrew/pull/47129)
- [x] neatvi.rb: upstream has [tagged releases](http://repo.or.cz/neatvi.git/shortlog/refs/tags/04) (#244)
- [x] osmfilter.rb: upstream has [tagged releases](https://gitlab.com/osm-c-tools/osmctools/tags) (#246)
- [ ] pdftoipe.rb: importing into core (https://github.com/Homebrew/homebrew-head-only/pull/256, https://github.com/Homebrew/homebrew-core/pull/8373)
- [x] shairport.rb: imported into core (https://github.com/Homebrew/homebrew/pull/46067)
- [x] tcpstat.rb: imported into core (https://github.com/Homebrew/homebrew/pull/46068)
- [x] termbox.rb (https://github.com/nsf/termbox/issues/82, https://github.com/Homebrew/homebrew-core/pull/4192)
- [x] titlecase.rb: imported into core (https://github.com/Homebrew/homebrew/pull/46116)
- [x] urbit.rb (https://github.com/Homebrew/homebrew-head-only/pull/205#discussion_r84934311, https://github.com/Homebrew/homebrew-head-only/pull/226)
- [x] willgit.rb: upstream tagged a [`1.0.0` release](https://github.com/DanielVartanov/willgit/releases/tag/1.0.0) (https://github.com/DanielVartanov/willgit/issues/1, https://github.com/Homebrew/homebrew-head-only/pull/243)
- [x] zzz.rb: imported into core (https://github.com/Homebrew/homebrew/pull/46076)

## Boneyarded
- [x] adept.rb: asked upstream for a release in Nov '15 (https://github.com/technopagan/adept-jpg-compressor/issues/29#issuecomment-157325655); no response since (https://github.com/Homebrew/homebrew-boneyard/pull/211)
- [x] afew.rb: asked upstream for a release in Nov '15 (https://github.com/teythoon/afew/issues/53#issuecomment-157325901); no response since (https://github.com/Homebrew/homebrew-boneyard/pull/212)
- [x] bd.rb: asked upstream for a release in Nov '15 (https://github.com/vigneshwaranr/bd/issues/13#issuecomment-157326012); no response since (https://github.com/Homebrew/homebrew-boneyard/pull/213)
- [x] bonnie.rb: asked upstream for a release in Jan '16 (email); no response since (https://github.com/Homebrew/homebrew-boneyard/pull/214)
- [x] bbcp.rb: asked upstream for a release in Jan '16 (email); no response since (https://github.com/Homebrew/homebrew-boneyard/pull/215)
- [x] daala.rb: upstream won’t tag a release before (at least) the end of 2016 ([mailing list](http://lists.xiph.org/pipermail/daala/2016-January/000119.html), https://github.com/Homebrew/homebrew-boneyard/pull/181)
- [x] darwinbuild.rb (https://github.com/Homebrew/homebrew-boneyard/pull/89)
- [x] depot-tools.rb: upstream won’t tag releases in the near future ([mailing list](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/bxbEgId5jt0), https://github.com/Homebrew/homebrew-boneyard/pull/179)
- [x] despotify.rb: asked upstream for a release in Feb '16 (email); no response since (https://github.com/Homebrew/homebrew-head-only/pull/232)
- [x] disque.rb: actively maintained, _may_ get a stable release in the future (https://github.com/Homebrew/homebrew-boneyard/pull/183)
- [x] f2c.rb: asked upstream for a release (email but host is down, https://github.com/Homebrew/homebrew-head-only/pull/222)
- [x] fssh.rb asked upstream for a release in Jan '16 (https://github.com/kylemanna/fssh/issues/3); no response since (https://github.com/Homebrew/homebrew-head-only/pull/233)
- [x] figtoipe.rb: upstream won’t tag a release (https://github.com/otfried/ipe-tools/issues/5, https://github.com/Homebrew/homebrew-boneyard/pull/149)
- [x] gccxml.rb (https://github.com/Homebrew/homebrew-boneyard/pull/93)
- [x] gitstats.rb: upstream won’t tag a release (https://github.com/hoxu/gitstats/issues/58, https://github.com/Homebrew/homebrew-boneyard/pull/150)
- [x] git-hg.rb: asked upstream for a release in Feb '16 (https://github.com/cosmin/git-hg/issues/55); no response since (https://github.com/Homebrew/homebrew-head-only/pull/234)
- [x] kakoune.rb: asked upstream for a release in Aug '16 (https://github.com/mawww/kakoune/issues/315); no upstream activity since Jan '16 (#248)
- [x] kati.rb: upstream won’t tag a release (https://github.com/google/kati/issues/38, https://github.com/Homebrew/homebrew-boneyard/pull/182)
- [x] lastfm_fplib.rb: no upstream activity since at least ~2010 (https://github.com/Homebrew/homebrew-head-only/pull/235)
- [x] libemu.rb (#249)
- [x] open-sg.rb: upstream appears to have [stable releases](http://www.opensg.org/wiki/Releases) but I can’t find any source tarball (#253)
- [x] otx.rb: No upstream activity since 2014 (#247)
- [x] qt-mobility.rb: upstream has [tagged releases](https://code.qt.io/cgit/qt-mobility/qt-mobility.git/tag/?h=v1.2.0) but they require `qt`. (#252)
- [x] redis-tools.rb: abandonned (https://github.com/antirez/redis-tools/issues/9#issuecomment-157329972, https://github.com/Homebrew/homebrew-boneyard/pull/151)
- [x] shaper-probe.rb: no upstream activity since 2013 (https://github.com/Homebrew/homebrew-head-only/pull/236)
- [x] sigar.rb: upstream has [tagged releases](https://github.com/hyperic/sigar/releases) but they don’t build on 10.8+ (https://github.com/hyperic/sigar/issues/47, #250)
- [x] squishyball.rb (https://github.com/Homebrew/homebrew-head-only/pull/241)
- [x] stp.rb (https://github.com/Homebrew/homebrew-head-only/pull/187)
- [x] tsocks.rb: no upstream activity since 2010 (https://github.com/Homebrew/homebrew-head-only/pull/237)
- [x] uniset.rb: unstable; upstream won’t tag a release (https://github.com/depp/uniset/issues/1, https://github.com/Homebrew/homebrew-head-only/pull/238)
- [x] vcontrold.rb: ~~it has versioned releases on [SourceForge](https://sourceforge.net/projects/vcontrold/)~~ Those are Windows binaries. (#251)
- [x] vdfuse.rb: asked upstream for a release in Oct '16 (https://github.com/SophosLabs/vdfuse/issues/2). No upstream activity since 2014. (#254)
- [x] woff2.rb: asked upstream for a release in Nov '15 (https://github.com/google/woff2/issues/40); no response since (https://github.com/Homebrew/homebrew-head-only/pull/239)
- [x] wol.rb: no upstream release since 2011 (https://github.com/Homebrew/homebrew-head-only/pull/240)
- [x] word2vec.rb (https://github.com/Homebrew/homebrew-head-only/pull/242)

## Removed
- [x] arcanist.rb: there’s the same formula in homebrew/php (https://github.com/Homebrew/homebrew-head-only/commit/7ee85a2eb2dfbececbfba47e35fc053c0d129c18)
- [x] libgarmin.rb: no response from upstream (email in Oct '16); no install (https://github.com/Homebrew/homebrew-head-only/issues/186#issuecomment-183991769)
- [x] libphenom.rb: no response from upstream (https://github.com/facebook/libphenom/issues/82); no install (https://github.com/Homebrew/homebrew-head-only/issues/186#issuecomment-183991769)
- [x] libvterm.rb: already exists in core
- [x] opentracker.rb: no response from upstream (email in Oct '16); no install (https://github.com/Homebrew/homebrew-head-only/issues/186#issuecomment-183991769)

Last update: 2017/01/02

**Comment by rwhogg** [comment]
moz-git-tools has a stable version now; since I originally committed it, I'll help import it.

**Comment by bfontaine** [comment]
Thanks @rwhogg!

**Comment by iMichka** [comment]
gccxml.rb can be deleted. It will not work anyway with newer compilers.

There is a replacement, https://github.com/CastXML/CastXML, but for the moment it has no tag. I have a formula ready for it which works nicely.

Debian packagers just use the short sha1 + the date as tag number when there are no tags. Would that not be a very easy solution to implement in homebrew ? I wanted to add CastXML here but saw that this tap is now deprecated ... too bad. Of course I could help work on this if you think this is a good idea.

**Comment by bfontaine** [comment]
@iMichka Do you know if they plan to tag it at some point?

> Debian packagers just use the short sha1 + the date as tag number when there are no tags. Would that not be a very easy solution to implement in homebrew ?

We’d have to edit the formula for each new commit in order to keep up-to-date; that’d be a lot of work :cry: 

Regarding the `HEAD` upgrading issue it’s one of our project suggestions for the upcoming Google Summer of Code: https://github.com/Homebrew/Google-Summer-of-Code#better-support-head-formulae-httpsgithubcomhomebrewhomebrewissues13197

**Comment by iMichka** [comment]
> We’d have to edit the formula for each new commit in order to keep up-to-date; that’d be a lot of work :cry:

We don't. We could just pick a commit at a point T, and that would be the one released on homebrew. The debian package maintainers also just picked one of the last commits. Looking at the debian package of custom, they had 5 version changes since June 2015. Not overwhelming.

I opened a pull request for castxml here, the discussion can continue there: https://github.com/Homebrew/homebrew/pull/49096

For GCCXML, should I make a PR to delete the formula ? We can safely delete it as it does not build anyway.

**Comment by bfontaine** [comment]
> For GCCXML, should I make a PR to delete the formula ?

That’d be great! However note we don’t delete formulae, we move them to [`homebrew/boneyard`](https://github.com/Homebrew/homebrew-boneyard). Please make a PR on this repo that removes it (with a commit like `gccxml: migrate to homebrew/x11`) and another on [`homebrew/boneyard`](https://github.com/Homebrew/homebrew-boneyard) that adds it. In each PR post a link to the other. Thanks!

**Comment by iMichka** [comment]
Done:
https://github.com/Homebrew/homebrew-head-only/pull/203
https://github.com/Homebrew/homebrew-boneyard/pull/93

**Comment by mikemcquaid** [comment]
Agreed to deprecating this 👍

**Comment by MikeMcQuaid** [comment]
@bfontaine any news here?

**Comment by bfontaine** [comment]
@MikeMcQuaid This tap is deprecated since 17215f163f00e710b855ec0d958e42b72f05957e but I haven’t tried to contact more project owners to ask for stable releases since your last comment.

**Comment by MikeMcQuaid** [comment]
@bfontaine 🆒. I think we can start just tearing down this tap and moving things to the boneyard, maybe?

**Comment by bfontaine** [comment]
@MikeMcQuaid Yep. I’m :beers:ing tonight; I’ll work on that by the end of the week.

**Comment by MikeMcQuaid** [comment]
@bfontaine No rush!

**Comment by otfried** [comment]
pdftoipe.rb:  Upstream now has a release tag.  The current release is v7.2.6

**Comment by MikeMcQuaid** [comment]
@bfontaine None of the remaining formulae have any installs since records began so I think we can just delete (not even boneyard) them all now.

**Comment by bfontaine** [comment]
@MikeMcQuaid Cool; I just removed them. Regarding `pdftoipe` last time I tried the tagged release was so different from the HEAD-only one that I wasn’t able to install it correctly. I’ll check what I can do tomorrow so we can close this issue before 2017 comes.

**Comment by miccal** [comment]
@bfontaine I use `pdftoipe` extensively - is there anything I can do to help? 

The only issue I have with `pdftoipe` is that every time `poppler` is updated I have to `brew reinstall -HEAD pdftoipe`, otherwise it works perfectly.

**Comment by ilovezfs** [comment]
@miccal the formula just needs to use https://dl.bintray.com/otfried/generic/ipe/7.2/ipe-7.2.7-src.tar.gz which otfried posted per our request.

**Comment by miccal** [comment]
@ilovezfs I do not think `pdftoipe` is part of the `Ipe` source files?

**Comment by ilovezfs** [comment]
@miccal yes it does seem to be missing. @otfried are the sources for the tools for 7.2.7 supposed to be in that tarball or do I have the link wrong?

**Comment by otfried** [comment]
No, the sources for pdftoipe are not in the Ipe tarball (as pdftoipe doesn't link to any Ipe library, but rather to poppler).

The sources are in the repository https://github.com/otfried/ipe-tools in the subdirectory `pdftoipe`.

I thought I created a release tag (as requested in https://github.com/otfried/ipe-tools/issues/5), but I cannot find it now. Maybe I forgot to push the tag.  I've now tagged the current version, so you can use this release in homebrew recipes:

https://github.com/otfried/ipe-tools/releases/tag/v7.2.7

**Comment by ilovezfs** [comment]
@otfried thank you!

@miccal do you mind opening a PR to homebrew/core using that tag?

**Comment by miccal** [comment]
@ilovezfs I would be happy to try - here is what I _think_ the `pdftoipe.rb` formula would look like:
```
class Pdftoipe < Formula
  desc "Drawing editor for creating figures in PDF"
  homepage "https://github.com/otfried/ipe-tools"
  url "https://github.com/otfried/ipe-tools/archive/v7.2.7.zip"
  version "7.2.7"
  sha256 "920f477b7470e0ddce636e49e9716021219747b11c27828682641f27083c218f"

  depends_on "pkg-config" => :build
  depends_on "poppler"

  def install
    cd "pdftoipe" do
      system "make"
      bin.install "pdftoipe"
      man1.install "pdftoipe.1"
    end
  end
end
```

However, I have no idea how to create a `test`?

**Comment by ilovezfs** [comment]
@miccal you don't need to specify the version explicitly since that's already detected correctly from the URL. Also you should use the tar.gz (https://github.com/otfried/ipe-tools/archive/v7.2.7.tar.gz) not the zip or you'll get an audit failure.

As for a test, this should work:
```
  test do
    cp test_fixtures("test.pdf"), testpath
    system bin/"pdftoipe", "test.pdf"
    assert_match "Homebrew test.</text>", File.read("test.ipe")
  end
```

**Comment by MikeMcQuaid** [comment]
Also: is it worth just having a single formula for `ipe-tools` for which `pdftoipe` is an alias?

**Comment by ilovezfs** [comment]
Probably so, but that would be a bit more of an undertaking since there's no top level Makefile.

**Comment by miccal** [comment]
@ilovezfs so like this:

```
class Pdftoipe < Formula
  desc "Drawing editor for creating figures in PDF"
  homepage "https://github.com/otfried/ipe-tools"
  url "https://github.com/otfried/ipe-tools/archive/v7.2.7.tar.gz"
  version "7.2.7"
  sha256 "889cb31bd8769ba111f541ba795cf53fad474aeeafbc87b7cd37c8a24b2dc6f6"

  depends_on "pkg-config" => :build
  depends_on "poppler"

  def install
    cd "pdftoipe" do
      system "make"
      bin.install "pdftoipe"
      man1.install "pdftoipe.1"
    end
  end

  test do
    cp test_fixtures("test.pdf"), testpath
    system bin/"pdftoipe", "test.pdf"
    assert_match "Homebrew test.</text>", File.read("test.ipe")
  end
end
```

I used to use MacPorts and their version of this is called `Ipe-tools` as you can see [here](https://github.com/macports/macports-ports/blob/master/graphics/ipe-tools/Portfile). I remember that this was always a pain with the other tools it installed - I personally would prefer this to just install `pdftoipe`.

**Comment by ilovezfs** [comment]
@miccal yup, just need to remove the `version "7.2.7"` line.

**Comment by miccal** [comment]
Submitted [here](https://github.com/Homebrew/homebrew-core/pull/8373).

I am a member of [Cask](https://github.com/orgs/caskroom/people), but have never contributed to Homebrew itself - please be gentle!

**Comment by miccal** [comment]
> Also you should use the tar.gz (https://github.com/otfried/ipe-tools/archive/v7.2.7.tar.gz) not the zip or you'll get an audit failure.

Purely to satisfy my curiosity, why is this?

**Comment by ilovezfs** [comment]
>Purely to satisfy my curiosity, why is this?

Standardization and a bit better compression.

**Comment by miccal** [comment]
Thanks for the explanation @ilovezfs.

**Comment by MikeMcQuaid** [comment]
Great work here @bfontaine and everyone 👏
